services:
  os_web:
    container_name: os_web
    image: nginx:alpine  # Use the Nginx image
    ports:
      - "9000:80"  # Map port 8080 on the host to port 80 inside the container
    volumes:
      - ./:/var/www  # Mount the Laravel application directory
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Use our Nginx config
    depends_on:
      - os_app  # Ensure PHP-FPM is started before Nginx
    networks:
      - os-network  # Connect to the custom network

  os_app:
    container_name: os_app
    build: .  # Build from the Dockerfile
    depends_on:
      - os_db
    volumes:
      - ./:/var/www  # Mount the Laravel application directory
    networks:
      - os-network  # Connect to the custom network

  os_db:
    container_name: os_db
    image: mysql:8  # Use MySQL image
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: online_store  # Create a database named 'laravel'
      MYSQL_ROOT_PASSWORD: root  # Set the root password for MySQL
    volumes:
      - os_db:/var/lib/mysql  # Persist MySQL data
    networks:
      - os-network  # Connect to the custom network

  os_node:
    container_name: os_node
    image: node:20
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - os-network
    command: bash -c "npm install && npm run build"
# Define the custom network
networks:
  os-network:  # Create a custom network named 'os-network'
    driver: bridge

# Define the volume for MySQL data persistence
volumes:
  os_db:
